---
baseurl: "http://stage.docs.camunda.org"
languageCode: "en-us"
title: "Camunda BPM documentation"
theme: "camunda"

blackfriday:
  plainIdAnchors: true

params:
  github:
    repositoryName: "camunda/docs.camunda.org"
    branch: "master"
...
