---
baseurl: "/manual/7.4"
languageCode: "en-us"
title: "Camunda BPM documentation"
theme: "camunda"

blackfriday:
  plainIdAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
  section:
    id: "manual"
    version: "7.4"
    versions:
      - "7.4"
      - "7.3"
      - "7.2"
      - "7.1"
      - "7.0"
  github:
    repositoryName: "camunda/docs.camunda.org"
    branch: "master"
...
